name: Steph Danforth
favicon: null
layout_spectrum: 0.8888276081997901
typography_spectrum: 0.6074010070879012
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.11009721108712256
  lightness: 0.8834633780643344
  saturation: 0.374112103600055
  rhythmicContrast: 0.1707249644678086
purpose: []
